### Authentication Endpoints
@Token=gDRV9ETNebnAOz-qAhJy3OVBvQp_s8mNnVGZHYuCC4INInCLWZI_9Av45mpc1Vdp
@AdminToken=oN3_otpYw84TQDgnANGLd4PJTQmOhNRFxC5DDrsLEG-MvpSPaCCUKrHTac11gmrd
###
POST http://127.0.0.1:8000/api/v1/library/auth/register/
Content-Type: application/json

{
    "username": "newmember",
    "password": "password123",
    "phone_number": "1234567890"
}

###
POST http://127.0.0.1:8000/api/v1/library/auth/login/
Content-Type: application/json

{
    "username": "newmember",
    "password": "password123"
}

###
POST http://127.0.0.1:8000/api/v1/library/auth/logout/
Authorization: Token {{Token}}


### Public Endpoints (AllowAny)

GET http://127.0.0.1:8000/api/v1/library/authors/

###
GET http://127.0.0.1:8000/api/v1/library/authors/2/

###
GET http://127.0.0.1:8000/api/v1/library/books/

###
GET http://127.0.0.1:8000/api/v1/library/books/3/


### Admin Endpoints (IsStaff)

GET http://127.0.0.1:8000/api/v1/library/admin/authors/
Authorization: Token {{AdminToken}}

###
POST http://127.0.0.1:8000/api/v1/library/admin/authors/
Content-Type: application/json
Authorization: Token {{AdminToken}}

{
    "name": "New Author2",
    "bio": "Author biography"
}

###
PUT http://127.0.0.1:8000/api/v1/library/admin/authors/1/
Content-Type: application/json
Authorization: Token {{AdminToken}}

{
    "name": "Updated Author",
    "bio": "Updated biography"
}

###
PATCH http://127.0.0.1:8000/api/v1/library/admin/authors/1/ 
Content-Type: application/json
Authorization: Token {{AdminToken}}

{
    "bio": "Partially updated biography"
}
###Change repo to accept partial
###
DELETE http://127.0.0.1:8000/api/v1/library/admin/authors/1/
Authorization: Token {{AdminToken}}

###
#                    books
###
GET http://127.0.0.1:8000/api/v1/library/admin/books/
Authorization: Token {{AdminToken}}

###
POST http://127.0.0.1:8000/api/v1/library/admin/books/
Content-Type: application/json
Authorization: Token {{AdminToken}}

{
    "title": "New Book2",
    "author_id": 2,
    "isbn": "12444567890",
    "total_copies": 5
}

###
GET http://127.0.0.1:8000/api/v1/library/admin/members/
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/members/?username=admin&phone_number=123
Authorization: Token {{AdminToken}}

###
POST http://127.0.0.1:8000/api/v1/library/admin/members/
Content-Type: application/json
Authorization: Token {{AdminToken}}

{
    "username": "newmember by admin",
    "password": "password123",
    "phone_number": "1234567890",
    "is_staff": false
}

###
GET http://127.0.0.1:8000/api/v1/library/admin/members/1/
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/members/1/borrowed-books/
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/member-books/
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/member-books/?member_username=john
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/member-books/?order_by=+due_date
Authorization: Token {{AdminToken}}

###
POST http://127.0.0.1:8000/api/v1/library/admin/member-books/
Content-Type: application/json
Authorization: Token {{AdminToken}}

{
    "book_id": 5,
    "member_id": 3 ,
    "borrow_period_days": 3
}

###
GET http://127.0.0.1:8000/api/v1/library/admin/member-books/4/
Authorization: Token {{AdminToken}}

###
POST http://127.0.0.1:8000/api/v1/library/admin/member-books/1/return/
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/member-books/overdue/
Authorization: Token {{AdminToken}}

###
GET http://127.0.0.1:8000/api/v1/library/admin/member-books/not-returned/
Authorization: Token {{AdminToken}}


### Member Endpoints (IsAuthorized)

GET http://127.0.0.1:8000/api/v1/library/member/books/
Authorization: Token {{Token}}

###
GET http://127.0.0.1:8000/api/v1/library/member/books/active/
Authorization: Token {{Token}}