# Generated by Django 5.2.7 on 2025-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
