# Generated by Django 5.2.7 on 2025-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_book_description_borrowedbook_is_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
