# Generated by Django 5.2.7 on 2025-10-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_book_available_copies_book_borrowed_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
