# Generated by Django 5.2.7 on 2025-10-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_borrowedbook_borrowed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='is_returned',
        ),
    ]
